import Head from 'next/head'
import { Layout, Typography, } from 'antd';

export default function Home() {
    return (
        <>
            <Head>
                <title>Pokeapp</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            Aboooout
        </>
    )
}
