import { useEffect, useState } from 'react';
import Head from 'next/head'
import { Modal, Row, Spin, Col, Input } from 'antd';
import PokemonCard from '@/components/pokemon';

export default function Home() {
  const [isModalVisible, toggleModal] = useState(false);
  const [allPokemons, setAllPokemons] = useState([]);
  const [searchTerm, setSearchTerm] = useState('');

  const filteredPokemons = allPokemons.filter(pokemon => pokemon.name.toLowerCase().includes(searchTerm.toLowerCase())); // <-- Filtered list of pokemons based on search term

  const getAllPokemons = async () => {
    const res = await fetch("https://pokeapi.co/api/v2/pokemon?limit=151")
    const data = await res.json()
    const detailedData = await Promise.all(data.results.map(async (pokemon) => {
      const res = await fetch(`https://pokeapi.co/api/v2/pokemon/${pokemon.name}`)
      return await res.json();
    }));
    setAllPokemons(detailedData);
  }

  // useEffect(() => {
  //   toggleModal(true);
  // }, []);


  useEffect(() => {
    getAllPokemons()
  }, [])

  if (allPokemons.length === 0) return <Spin />;

  return (
    <>
      <Head>
        <title>Pokeapp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Input
        placeholder="Search Pokemon"
        value={searchTerm}
        onChange={(e) => setSearchTerm(e.target.value)}
        style={{ marginBottom: '20px' }}
      />
      <Row gutter={[12, 12]}>
        {filteredPokemons?.map(pokemon => <Col xs={{ span: 24 }} sm={{ span: 12 }} lg={{ span: 6 }}>
          <PokemonCard pokemon={pokemon} toggleModal={toggleModal} />
        </Col>)}
      </Row>
      <Modal title="It's a catch!" open={isModalVisible} onOk={() => toggleModal(false)} onCancel={() => toggleModal(false)} />
    </>
  )
}
